### ISSUE TITLE
Have you considered adding Word to Vector mapping?

### ISSUE THREAD

**Issue by xumx** [winkjs/wink-nlp-utils#10]
I'm referring to Word Embeddings.

**Comment by prtksxna** [comment]
Hey @xumx, that is a great idea, thanks! 😄 

It has been on our roadmap for a while but we haven't been able to get to it yet. But, whenever we do it won't be part of `wink-nlp-utils` but a different package. So, I'll be closing this issue for now, but will leave a link here whenever we start work on it.

**Comment by sanjayaksaxena** [comment]
Hi @xumx 

We are not sure about your exact requirement. It will be nice if you could share the same.

You may like to explore at [`wink-tokenizer`](https://www.npmjs.com/package/wink-tokenizer), [`wink-pos-tagger`](https://www.npmjs.com/package/wink-pos-tagger), [`wink-sentiment`](https://www.npmjs.com/package/wink-sentiment) and [`wink-distance`](https://www.npmjs.com/package/wink-distance). We have initiated work on [wink named entity recognition](https://github.com/winkjs/wink-lookup-ner) and expect to release them in next 2-3 weeks. Some of these packages have multilingual support (more to follow).
