### ISSUE TITLE
Improve ngram - bigram function

### ISSUE THREAD

**Issue by giorgio79** [winkjs/wink-nlp-utils#15]
The ngram is for string, while the bigram is for tokens. Wondered if tokens could have a more generic ngram function where you can feed in the maximum gram as a parameter? 

http://winkjs.org/wink-nlp-utils/#tokensbigrams

So we could have sg like this https://github.com/nlp-compromise/nlp-ngram

**Comment by rachnachakraborty** [comment]
Hi @giorgio79,

This feature is in our roadmap.

Best,
Rachna
