### ISSUE TITLE
Could we add our own abbreviations for the sentence boundary detection?

### ISSUE THREAD

**Issue by chrislim** [winkjs/wink-nlp-utils#30]
The current list of abbreviations in the sentence boundary detection code is quite limited. Could we have the option of passing in other abbreviations to be considered so that we do not have sentences broken up in incorrect places?

**Comment by sanjayaksaxena** [comment]
Hello @chrislim 

Right now such capability does not exist. But we can surely explore that.

In the meantime, you may like to explore [wink-nlp](https://github.com/winkjs/wink-nlp#readme). Its comprehensive documentation is available at https://winkjs.org/wink-nlp/getting-started.html.
