### ISSUE TITLE
`extractPersonsName` Not working as expected

### ISSUE THREAD

**Issue by reginsmol** [winkjs/wink-nlp-utils#34]
Code: 
```
const nlp = require('wink-nlp-utils');

nlp.string.extractPersonsName('George Washington was an American military officer, statesman, and Founding Father who served as the first president of the United States from 1789 to 1797.')
```

Expected behavior: return `George Washington`

Actual Behavior: returns `George Washington was an American military officer statesman and Founding Father who served as the first president of the United States from to`

Reproduction: https://runkit.com/embed/glyj5qvv8rgi

**Comment by sanjayaksaxena** [comment]
Hi @reginsmol 

It is not named entity extraction. 

It assmues the following name format:
`[<salutations>] <name part as FN [MN] [LN]> [<degrees>]` and extracts the name from such a text string. Entities in square brackets are optional.

Please refer to the documentation for details https://winkjs.org/wink-nlp-utils/string.html#extractPersonsName

Best,
Sanjaya
